-- Naive homogenization of the symplectic Stiefel ideal I_{k,n}
--
-- spStiefelHomogeneousIdeal(k,n) constructs a 2k x 2n matrix X with
-- entries x_i_j, introduces an additional indeterminate z, and returns
-- the ideal generated by the entries of
--
--                 X O_n X^T - z^2 O_k.
--
-- QQ is used as the exact characteristic-zero coefficient field.

spStiefelHomogeneousIdeal = (k, n) -> (
    if not instance(k, ZZ) or not instance(n, ZZ) then
        error "k and n must be integers";
    if k < 1 then
        error "k must be positive";
    if n < k then
        error "n must satisfy n >= k";

    variableNames := flatten apply(1..(2*k), i ->
        apply(1..(2*n), j ->
            getSymbol("x_" | toString(i) | "_" | toString(j))));

    R := QQ[variableNames | {getSymbol "z"}];
    X := genericMatrix(R, first gens R, 2*k, 2*n);
    zR := last flatten entries gens R;

    In := id_(R^n);
    Ik := id_(R^k);
    Zn := 0 * In;
    Zk := 0 * Ik;

    On := (Zn || In) ++ (-In || Zn);
    Ok := (Zk || Ik) ++ (-Ik || Zk);

    ideal flatten entries(X * On * transpose X - zR^2 * Ok)
);

-- Example:
-- J = spStiefelHomogeneousIdeal(2, 3);
-- gens ring J
-- numgens J
